### ISSUE TITLE
Automate release management

### ISSUE THREAD

**Issue by georgms** [findologic/dokuwiki-plugin-findologic-xml-export#33]
Use [GitHub Releases Uploading](https://docs.travis-ci.com/user/deployment/releases/#stq=&stp=0) to automate release management.

**Comment by georgms** [comment]
Accidentally closed

**Comment by TheKeymaster** [comment]
What to do:

Add release version number to `composer.json`.
Create `workflow.md` and write data what needs to be done in order to create a new release etc.

1. If something is merged to master, go into deploy stage
    - This means clean up everything.
2. Create a Tag based on the `composer.json` release version number.
3. Zip archive and upload it to GitHub (May be easier)
4. (optional) Create `CHANGELOG.md` for all changes.

**Comment by TheKeymaster** [comment]
This issue was fixed by #47.
